name: CI

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
      - next/*
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - next/*

jobs:
  bundles:
    name: Check Bundles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check Bundles
        shell: bash
        run: |
          dirty_workspaces=()
          for input_workspace in `find src -depth 1 -type d -not -name node_modules` ; do
            output_workspace=$(echo $input_workspace | sed -e 's/^src/pkgs/')
            input_mtime=$(git log -1 --format=%ct $input_workspace)
            output_mtime=$(git log -1 --format=%ct $output_workspace)
            if [[ $input_mtime -gt $output_mtime ]] ; then
              echo "❌ $input_workspace has changed since $output_workspace was last generated"
              dirty_workspaces+=($input_workspace)
            fi
          done
          if [[ ${#dirty_workspaces[@]} -gt 0 ]] ; then
            echo
            echo 'Re-run `npm run bundle` on the following workspaces before committing:'
            for workspace in ${dirty_workspaces[*]} ; do
              echo "  • $workspace"
            done
            exit 1
          fi
